/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 投稿APIのOpenAPI定義。 */
        post: operations["create_message_endpoint_doc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** タイムライン取得APIのOpenAPI定義。 */
        get: operations["timeline_endpoint_doc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description メッセージ投稿リクエスト。 */
        CreateMessageRequest: {
            /** @description 投稿本文。 */
            body: string;
        };
        /** @description メッセージ投稿レスポンス。 */
        CreateMessageResponse: {
            /** @description 応答メッセージ。 */
            message: string;
            /** @description 処理ステータス。 */
            status: string;
        };
        /** @description エラーレスポンス。 */
        ErrorResponse: {
            /** @description エラー概要。 */
            message: string;
        };
        /** @description タイムライン取得レスポンス。 */
        TimelineMessageResponse: {
            /** @description 投稿本文。 */
            body: string;
            /**
             * Format: date-time
             * @description 投稿日時。
             */
            created_at: string;
            /** @description 利用者投稿かどうか。 */
            is_from_user: boolean;
            /** @description 投稿者名。 */
            user_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_message_endpoint_doc: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageRequest"];
            };
        };
        responses: {
            /** @description 投稿成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateMessageResponse"];
                };
            };
            /** @description 不正なリクエスト */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    timeline_endpoint_doc: {
        parameters: {
            query?: {
                /** @description ISO8601形式の境界日時 */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description タイムライン取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineMessageResponse"][];
                };
            };
            /** @description 不正なリクエスト */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
