AWSTemplateFormatVersion: '2010-09-09'
Description: SNSシステム レビュー資料管理インフラ

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - develop
      - release

Resources:
  ReviewMaterialsBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ReviewMaterialsOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${AWS::StackName}-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ReviewMaterialsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        DefaultRootObject: index.html
        Origins:
          - Id: review-materials-s3-origin
            DomainName: !GetAtt ReviewMaterialsBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt ReviewMaterialsOriginAccessControl.Id
        DefaultCacheBehavior:
          TargetOriginId: review-materials-s3-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

  ReviewMaterialsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReviewMaterialsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub ${ReviewMaterialsBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${ReviewMaterialsDistribution}

Outputs:
  BucketName:
    Value: !Ref ReviewMaterialsBucket
    Export:
      Name: !Sub sns-review-${Stage}-BucketName
  DomainName:
    Value: !GetAtt ReviewMaterialsDistribution.DomainName
    Export:
      Name: !Sub sns-review-${Stage}-DomainName
